export const state = () => ({
    finished: {
        "Stamina potion": { first: 3016, second: "3955, 3957, 3959, or 3961" },
        "Fishing potion": { first: 103, second: 231 },
        "Hunter potion": { first: 103, second: 10111 },
        "Super energy": { first: 103, second: 2970 },
        // "Weapon poison+": { first: 0, second: 0 },
        "Bastion potion": { first: 22443, second: 245 },
        "Battlemage potion": { first: 22443, second: 3138 },
        "Super defence": { first: 107, second: 239 },
        // "Weapon poison++": { first: 0, second: 0 },
        // "Super antifire potion": { first: 0, second: 0 },
        // "Divine bastion potion": { first: 0, second: 0 },
        // "Divine battlemage potion": { first: 0, second: 0 },
        // "Divine magic potion": { first: 0, second: 0 },
        // "Divine ranging potion": { first: 0, second: 0 },
        // "Divine super attack potion": { first: 0, second: 0 },
        // "Divine super combat potion": { first: 0, second: 0 },
        // "Divine super defence potion": { first: 0, second: 0 },
        // "Divine super strength potion": { first: 0, second: 0 },
        "Ranging potion": { first: 109, second: 245 },
        // "Imp repellent": { first: 0, second: 0 },
        // "Guthix balance": { first: 0, second: 0 },
        "Attack potion": { first: 91, second: 221 },
        "Blamish oil": { first: 97, second: 1581 },
        "Combat potion": { first: 97, second: 9736 },
        "Compost potion": { first: 97, second: 21622 },
        "Energy potion": { first: 97, second: 1975 },
        // "Guthix rest tea": { first: 97, second: 0 },
        "Restore potion": { first: 97, second: 223 },
        // "Antidote++": { first: 0, second: 0 },
        // "Super attack": { first: 0, second: 0 },
        // "Superantipoison": { first: 0, second: 0 },
        // "Super strength": { first: 0, second: 0 },
        // "Weapon poison": { first: 0, second: 0 },
        // "Antifire potion": { first: 0, second: 0 },
        // "Magic potion": { first: 0, second: 0 },
        // "Extended antifire": { first: 0, second: 0 },
        // "Extended super antifire": { first: 0, second: 0 },
        // "Antipoison": { first: 0, second: 0 },
        // "Defence potion": { first: 0, second: 0 },
        "Prayer potion": { first: 99, second: 231 },
        // "Relicym's balm": { first: 0, second: 0 },
        // "Super restore": { first: 0, second: 0 },
        // "Magic essence": { first: 0, second: 0 },
        // "Serum 207": { first: 0, second: 0 },
        // "Shrink-me-quick": { first: 0, second: 0 },
        // "Strength potion": { first: 0, second: 0 },
        // "Agility potion": { first: 0, second: 0 },
        // "Antidote+": { first: 0, second: 0 },
        // "Saradomin brew": { first: 0, second: 0 },
        // "Anti-venom+": { first: 0, second: 0 },
        // "Super combat potion": { first: 0, second: 0 },
        // "Zamorak brew": { first: 0, second: 0 },
        // "Sanfew serum": { first: 0, second: 0 },
        // "Anti-venom": { first: 0, second: 0 }
    },
    unfinished: {
        "Guam potion (unf)": { first: 227, second: 249 },
        "Marrentill potion (unf)": { first: 227, second: 251 },
        "Tarromin potion (unf)": { first: 227, second: 253 },
        "Harralander potion (unf)": { first: 227, second: 255 },
        "Ranarr potion (unf)": { first: 227, second: 257 },
        "Toadflax potion (unf)": { first: 227, second: 2998 },
        "Irit potion (unf)": { first: 227, second: 259 },
        "Avantoe potion (unf)": { first: 227, second: 261 },
        "Kwuarm potion (unf)": { first: 227, second: 263 },
        "Snapdragon potion (unf)": { first: 227, second: 3000 },
        "Cadantine potion (unf)": { first: 227, second: 265 },
        "Lantadyme potion (unf)": { first: 227, second: 2481 },
        "Dwarf weed potion (unf)": { first: 227, second: 267 },
        "Torstol potion (unf)": { first: 227, second: 269 }
    },
    tar: {
        "Guam tar": { first: 249, second: 1939 },
        "Marrentill tar": { first: 251, second: 1939 },
        "Tarromin tar": { first: 253, second: 1939 },
        "Harralander tar": { first: 255, second: 1939 }
    },
    banks: [
        {
            text: "Varrock West",
            value: {
                type: "Npc",
                id: 2897,
                opCode: 11,
            }
        }
    ]
});